"""Export stroke data as sorted JSON for the Chrome extension.

Characters with multiple stroke sequence variants (from Conway's regex
alternatives) are exported as separate entries so the binary-search prefix
match in the extension finds the character regardless of which stroke
convention the user follows.

Also applies Cantonese frequency overrides and exports bigram + trigram data.
"""
import sys, json
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "src"))

from stroke_input.data.serializer import load_msgpack
from stroke_input.data.phrase_loader import load_phrase_dict
from stroke_input.data.ngram_model import NgramModel
from stroke_input.data.ngram_export import export_trigrams_for_chrome, export_bigrams_for_chrome

records = load_msgpack(_ROOT / "data/stroke_db.msgpack")

# Load Cantonese frequency overrides if available
cantonese_freq_path = _ROOT / "chrome-extension/data/cantonese_freq.json"
cantonese_freq: dict[str, float] = {}
if cantonese_freq_path.exists():
    cantonese_freq = json.loads(cantonese_freq_path.read_text(encoding="utf-8"))
    print(f"Loaded {len(cantonese_freq)} Cantonese frequency overrides")

# Build sorted array: [sequence_string, character, frequency]
# Multiple entries per character are expected (one per stroke variant)
data = []
seen: set[tuple[str, str]] = set()
for r in records:
    seq = "".join(str(s) for s in r.stroke_sequence)
    key = (seq, r.character)
    if key not in seen:
        seen.add(key)
        # Apply Cantonese frequency override if available
        freq = r.frequency
        if r.character in cantonese_freq:
            freq = max(freq, cantonese_freq[r.character])
        data.append([seq, r.character, round(freq, 4)])

data.sort(key=lambda x: x[0])

out = _ROOT / "chrome-extension/data/strokes.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
print(f"{len(data)} entries, {out.stat().st_size:,} bytes")

# Phrases are now generated by generate_cantonese_data.py
# Only regenerate from TSV if the Cantonese phrases.json doesn't exist
phrases_json = _ROOT / "chrome-extension/data/phrases.json"
if not phrases_json.exists():
    phrases_path = _ROOT / "data/phrases.tsv"
    phrases = {}
    for line in phrases_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        phrase = parts[0].strip()
        freq = float(parts[1]) if len(parts) >= 2 else 0.0
        if len(phrase) >= 2:
            first = phrase[0]
            if first not in phrases:
                phrases[first] = []
            phrases[first].append([phrase, freq])

    for k in phrases:
        phrases[k].sort(key=lambda x: -x[1])

    phrases_json.write_text(json.dumps(phrases, ensure_ascii=False), encoding="utf-8")
    print(f"{sum(len(v) for v in phrases.values())} phrases, {phrases_json.stat().st_size:,} bytes")
else:
    print(f"Phrases already generated by generate_cantonese_data.py, skipping")

# ── Build NgramModel from phrase corpus and export bigrams + trigrams ────────
phrase_tsv = _ROOT / "data/phrases.tsv"
cantonese_phrases_tsv = _ROOT / "data/cantonese_phrases.tsv"

phrase_source = cantonese_phrases_tsv if cantonese_phrases_tsv.exists() else phrase_tsv

if phrase_source.exists():
    print(f"Building NgramModel from {phrase_source} ...")
    phrase_dict = load_phrase_dict(phrase_source)
    all_entries = [entry for entries in phrase_dict._index.values() for entry in entries]
    ngram = NgramModel.build_from_phrases(all_entries)
    print(f"  vocab={ngram.vocab_size}, bigram_contexts={len(ngram._bi)}, "
          f"trigram_contexts={sum(len(b) for b in ngram._tri.values())}")

    # Export bigrams.json (model-derived, replaces old co-occurrence version)
    bigrams_json = _ROOT / "chrome-extension/data/bigrams.json"
    if not bigrams_json.exists():
        bigram_data = export_bigrams_for_chrome(ngram, min_count=1)
        bigrams_json.write_text(json.dumps(bigram_data, ensure_ascii=False), encoding="utf-8")
        print(f"  bigrams.json: {len(bigram_data)} prev-contexts, {bigrams_json.stat().st_size:,} bytes")
    else:
        print(f"  bigrams.json already exists (generated by generate_cantonese_data.py), skipping")

    # Export trigrams.json (new — trigram context for enhanced ranking)
    trigrams_json = _ROOT / "chrome-extension/data/trigrams.json"
    trigram_data = export_trigrams_for_chrome(ngram, min_count=2)
    trigrams_json.write_text(json.dumps(trigram_data, ensure_ascii=False), encoding="utf-8")
    n_tri = sum(len(bi) for bi in trigram_data.values())
    print(f"  trigrams.json: {len(trigram_data)} p2-contexts, {n_tri} (p2,p1) pairs, "
          f"{trigrams_json.stat().st_size:,} bytes")
else:
    print(f"No phrase TSV found, skipping NgramModel export")
